// This file is auto-generated by scripts/fetch-orbit-chains.ts
// Last updated: 2026-01-01T03:31:15.651Z
// Do not edit manually

import { ChainMetadata } from './chains';

export const ORBIT_CHAINS: (ChainMetadata & { 
  isOrbitChain: true; 
  orbitMetadata: {
    parentChain: string;
    deployerTeam: string | null;
    status: string;
    layer: number | null;
    category: string;
  };
})[] = [
  {
    "id": "alienx-chain",
    "name": "AlienX",
    "shortName": "AlienX",
    "caip2": "eip155:10241024",
    "chainId": 10241024,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Caldera",
      "status": "Mainnet",
      "layer": 2,
      "category": "consumer"
    },
    "colors": {
      "light": [
        "#d5f462",
        "#d5f462"
      ],
      "dark": [
        "#d5f462",
        "#d5f462"
      ],
      "darkTextOnBackground": true
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#d5f462\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#d5f462\">A</text>",
      "width": 15,
      "height": 15
    },
    "description": "ALIENX is the only staking blockchain driven by AI nodes, built for the mass adoption of NFTs and games."
  },
  {
    "id": "apechain",
    "name": "ApeChain",
    "shortName": "ApeChain",
    "caip2": "eip155:33139",
    "chainId": 33139,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Caldera",
      "status": "Mainnet",
      "layer": 3,
      "category": "gaming"
    },
    "colors": {
      "light": [
        "#014abf",
        "#014abf"
      ],
      "dark": [
        "#014abf",
        "#014abf"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#014abf\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#014abf\">A</text>",
      "width": 15,
      "height": 15
    },
    "description": "ApeCoin blockchain that scales $APE and supports the growth of the ApeCoin ecosystem. Powered by the $APE token and the home of assets and games in the ApeCoin ecosystem with development and growth led by Horizen Labs. "
  },
  {
    "id": "app-chain",
    "name": "AppChain",
    "shortName": "AppChain",
    "caip2": "eip155:466",
    "chainId": 466,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": null,
      "status": "Mainnet",
      "layer": 2,
      "category": "consumer"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">A</text>",
      "width": 15,
      "height": 15
    },
    "description": "Building useful onchain apps. "
  },
  {
    "id": "dodo",
    "name": "BirdLayer",
    "shortName": "BirdLayer",
    "caip2": "eip155:53456",
    "chainId": 53456,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "AltLayer",
      "status": "Mainnet",
      "layer": 3,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#ffe804",
        "#ffe804"
      ],
      "dark": [
        "#ffe804",
        "#ffe804"
      ],
      "darkTextOnBackground": true
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#ffe804\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#ffe804\">B</text>",
      "width": 15,
      "height": 15
    },
    "description": "Omni-Trading Layer-3 connecting liquidity from all chains including BTC and ETH L2s. The first restaked rollup built using the orbit stack.  "
  },
  {
    "id": "blessnet",
    "name": "Blessnet",
    "shortName": "Blessnet",
    "caip2": "eip155:45513",
    "chainId": 45513,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": null,
      "status": "Mainnet",
      "layer": 3,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">B</text>",
      "width": 15,
      "height": 15
    },
    "description": "transact without fearing for your life each time you hit confirm."
  },
  {
    "id": "capx",
    "name": "Capx Chain",
    "shortName": "Capx Chain",
    "caip2": "eip155:757",
    "chainId": 757,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": null,
      "status": "Mainnet",
      "layer": 2,
      "category": "ai-and-depin"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">C</text>",
      "width": 15,
      "height": 15
    },
    "description": "Build, Own & Trade AI Agents"
  },
  {
    "id": "conwai",
    "name": "conwai",
    "shortName": "conwai",
    "caip2": "eip155:668668",
    "chainId": 668668,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Caldera",
      "status": "Mainnet",
      "layer": 3,
      "category": "ai-and-depin"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">C</text>",
      "width": 15,
      "height": 15
    },
    "description": "Life's a Game. AI Supralayer."
  },
  {
    "id": "corn",
    "name": "Corn",
    "shortName": "Corn",
    "caip2": "eip155:21000000",
    "chainId": 21000000,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 2,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#f5901a",
        "#f5901a"
      ],
      "dark": [
        "#f5901a",
        "#f5901a"
      ],
      "darkTextOnBackground": true
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#f5901a\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#f5901a\">C</text>",
      "width": 15,
      "height": 15
    },
    "description": "The Super Yield Network Rooted In Digital Gold."
  },
  {
    "id": "deri",
    "name": "Deri Chain",
    "shortName": "Deri Chain",
    "caip2": "eip155:20231119",
    "chainId": 20231119,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "AltLayer",
      "status": "Mainnet",
      "layer": 3,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#3756cd",
        "#3756cd"
      ],
      "dark": [
        "#3756cd",
        "#3756cd"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#3756cd\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#3756cd\">D</text>",
      "width": 15,
      "height": 15
    },
    "description": "The Deri Chain, abbreviated as dChain, is the dedicated AppChain and a core component of Deri V4. \n\nOur vision for Deri V4 is to build an all-chain, decentralized derivative trading protocol, enhancing the inclusivity, capital efficiency, and user experience in the DeFi derivatives market.\n\nAt the heart of Deri V4's transformative design lies the xDapp model, making the architecture of Deri V4's dChain and iChain pivotal. iChains act as the user interfaces for submitting requests, while the dChain is responsible for processing these requests from all iChains."
  },
  {
    "id": "ebi-xyz",
    "name": "ebi.xyz",
    "shortName": "ebi.xyz",
    "caip2": "eip155:98881",
    "chainId": 98881,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 2,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#fe3d3e",
        "#fe3d3e"
      ],
      "dark": [
        "#fe3d3e",
        "#fe3d3e"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#fe3d3e\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#fe3d3e\">E</text>",
      "width": 15,
      "height": 15
    },
    "description": "Unlocking liquidity on all tokens."
  },
  {
    "id": "edgeless-network",
    "name": "Edgeless Network",
    "shortName": "Edgeless Net",
    "caip2": "eip155:2026",
    "chainId": 2026,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Caldera",
      "status": "Mainnet",
      "layer": 2,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#a0eb6a",
        "#a0eb6a"
      ],
      "dark": [
        "#a0eb6a",
        "#a0eb6a"
      ],
      "darkTextOnBackground": true
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#a0eb6a\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#a0eb6a\">E</text>",
      "width": 15,
      "height": 15
    },
    "description": "Edgeless Network is the first protocol fee-free ecosystem built as an arbitrum nitro chain with eigenlayer’s DA solution. "
  },
  {
    "id": "edu-chain",
    "name": "EDU Chain",
    "shortName": "EDU Chain",
    "caip2": "eip155:41923",
    "chainId": 41923,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Gelato",
      "status": "Mainnet",
      "layer": 3,
      "category": "infra-and-tools"
    },
    "colors": {
      "light": [
        "#141beb",
        "#141beb"
      ],
      "dark": [
        "#141beb",
        "#141beb"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#141beb\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#141beb\">E</text>",
      "width": 15,
      "height": 15
    },
    "description": "EDU Chain is designed to onboard real-world educational economies to blockchain and create an ecosystem of decentralized applications (Dapps) to establish an innovative “Learn Own Earn” model for education. EDU Chain, the first decentralized blockchain for education built by Open Campus, helps to democratize education and empower all participants — learners, educators, edtech innovators — to contribute to and benefit from the future of education. Anyone can support the EDU Chain network by operating a node, which allows them to receive network rewards and participate in governance."
  },
  {
    "id": "ethereal",
    "name": "Ethereal Mainnet",
    "shortName": "Ethereal Mai",
    "caip2": "eip155:5064014",
    "chainId": 5064014,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 3,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">E</text>",
      "width": 15,
      "height": 15
    },
    "description": "Ethereal is a decentralized exchange offering institutional-grade performance (sub-20 ms latency, ~1M orders per second) with DeFi-enabled self-custody and security guarantees."
  },
  {
    "id": "evedex",
    "name": "Eventum",
    "shortName": "Eventum",
    "caip2": "eip155:161803",
    "chainId": 161803,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Gelato",
      "status": "Mainnet",
      "layer": 3,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#1f1267",
        "#1f1267"
      ],
      "dark": [
        "#1f1267",
        "#1f1267"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#1f1267\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#1f1267\">E</text>",
      "width": 15,
      "height": 15
    },
    "description": "Eventum Chain is a hybrid blockchain network (L3 solution) developed by the EVEDEX team, combining the security and transparency of decentralized exchanges (DEX) with the speed and efficiency of centralized platforms (CEX). It is built on Arbitrum Orbit and leverages its infrastructure to ensure fast and secure data exchange and transaction processing."
  },
  {
    "id": "fluence",
    "name": "Fluence",
    "shortName": "Fluence",
    "caip2": "eip155:9999999",
    "chainId": 9999999,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Gelato",
      "status": "Mainnet",
      "layer": 2,
      "category": "ai-and-depin"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">F</text>",
      "width": 15,
      "height": 15
    },
    "description": "Build & deploy apps on our cloudless compute platform."
  },
  {
    "id": "forta",
    "name": "Forta Chain",
    "shortName": "Forta Chain",
    "caip2": "eip155:80931",
    "chainId": 80931,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 3,
      "category": "infra-and-tools"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">F</text>",
      "width": 15,
      "height": 15
    },
    "description": "The Forta Chain is an L3 rollup with the core function of supporting the Forta Firewall. Forța Firewall îs an exploit prevention network for rollups that screens and blocks malicious transactions before execution."
  },
  {
    "id": "g7",
    "name": "G7",
    "shortName": "G7",
    "caip2": "eip155:2187",
    "chainId": 2187,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 3,
      "category": "gaming"
    },
    "colors": {
      "light": [
        "FF0000",
        "FF0000"
      ],
      "dark": [
        "FF0000",
        "FF0000"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"FF0000\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"FF0000\">G</text>",
      "width": 15,
      "height": 15
    },
    "description": "Game7 is an onchain gaming ecosystem where both players and developers win."
  },
  {
    "id": "gravity-chain",
    "name": "Gravity Chain",
    "shortName": "Gravity Chai",
    "caip2": "eip155:1625",
    "chainId": 1625,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 2,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#e57536",
        "#e57536"
      ],
      "dark": [
        "#e57536",
        "#e57536"
      ],
      "darkTextOnBackground": true
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#e57536\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#e57536\">G</text>",
      "width": 15,
      "height": 15
    },
    "description": "Galxe is a decentralized super app with a quest platform, identity solutions, reputation scores, an AI copilot, and more Galxe has 20M users doing more than 100M monthly transactions. They need a cutting-edge scaling solution to bring their product suite onchain"
  },
  {
    "id": "hpp",
    "name": "HPP",
    "shortName": "HPP",
    "caip2": "eip155:190415",
    "chainId": 190415,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 2,
      "category": "ai-and-depin"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">H</text>",
      "width": 15,
      "height": 15
    },
    "description": "From Aergo to HPP. The AI-native Layer 2 built for agents, data, and verifiable off-chain inference."
  },
  {
    "id": "jetstream",
    "name": "Jetstream",
    "shortName": "Jetstream",
    "caip2": "eip155:810512",
    "chainId": 810512,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 3,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">J</text>",
      "width": 15,
      "height": 15
    },
    "description": "Not another perp DEX. Real futures. Real clearing."
  },
  {
    "id": "lasernet",
    "name": "Lasernet by DIA",
    "shortName": "Lasernet by ",
    "caip2": "eip155:1050",
    "chainId": 1050,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 2,
      "category": "infra-and-tools"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">L</text>",
      "width": 15,
      "height": 15
    },
    "description": "DIA Lumina is a new oracle architecture with an ETH layer-2 at its core. DIA Lumina brings fully on-chain, verifiable, and trustless data through its permissionless and modular design."
  },
  {
    "id": "logx",
    "name": "LogX",
    "shortName": "LogX",
    "caip2": "eip155:936369",
    "chainId": 936369,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "AltLayer",
      "status": "Mainnet",
      "layer": 2,
      "category": "infra-and-tools"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">L</text>",
      "width": 15,
      "height": 15
    },
    "description": "Building world's first Modular Derivatives Infra for Infinite Scalability Across All Blockchain Networks."
  },
  {
    "id": "mindchain",
    "name": "MindChain",
    "shortName": "MindChain",
    "caip2": "eip155:228",
    "chainId": 228,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "AltLayer",
      "status": "Mainnet",
      "layer": 3,
      "category": "infra-and-tools"
    },
    "colors": {
      "light": [
        "#6B7280",
        "#9CA3AF"
      ],
      "dark": [
        "#6B7280",
        "#9CA3AF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#6B7280\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#6B7280\">M</text>",
      "width": 15,
      "height": 15
    },
    "description": "An FHE restaking Layer for PoS and AI networks."
  },
  {
    "id": "oev-network",
    "name": "OEV Network",
    "shortName": "OEV Network",
    "caip2": "eip155:4913",
    "chainId": 4913,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Caldera",
      "status": "Mainnet",
      "layer": 2,
      "category": "infra-and-tools"
    },
    "colors": {
      "light": [
        "#1828bc",
        "#1828bc"
      ],
      "dark": [
        "#1828bc",
        "#1828bc"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#1828bc\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#1828bc\">O</text>",
      "width": 15,
      "height": 15
    },
    "description": "Oracles that pay you. "
  },
  {
    "id": "playblock",
    "name": "Playnance",
    "shortName": "Playnance",
    "caip2": "eip155:1829",
    "chainId": 1829,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Gelato",
      "status": "Mainnet",
      "layer": 3,
      "category": "gaming"
    },
    "colors": {
      "light": [
        "#f30104",
        "#f30104"
      ],
      "dark": [
        "#f30104",
        "#f30104"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#f30104\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#f30104\">P</text>",
      "width": 15,
      "height": 15
    },
    "description": "The team behind #1 game on Polygon, Playnance, is building a gasless gaming L3 on top of Arbitrum Nova. "
  },
  {
    "id": "plume",
    "name": "Plume Network",
    "shortName": "Plume Networ",
    "caip2": "eip155:98866",
    "chainId": 98866,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Caldera",
      "status": "Mainnet",
      "layer": 2,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#f43b39",
        "#f43b39"
      ],
      "dark": [
        "#f43b39",
        "#f43b39"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#f43b39\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#f43b39\">P</text>",
      "width": 15,
      "height": 15
    },
    "description": "Plume is the first modular L2 blockchain dedicated for all real-world assets (RWAs) that integrates asset tokenization and compliance providers directly into the chain. Our mission is to simplify the convoluted processes of RWA project deployment and offer investors a blockchain ecosystem to cross-pollinate and invest in various RWAs."
  },
  {
    "id": "powerloom",
    "name": "Powerloom Mainnet V2",
    "shortName": "Powerloom Ma",
    "caip2": "eip155:7869",
    "chainId": 7869,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 2,
      "category": "infra-and-tools"
    },
    "colors": {
      "light": [
        "55E794",
        "161818"
      ],
      "dark": [
        "55E794",
        "161818"
      ],
      "darkTextOnBackground": true
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"55E794\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"55E794\">P</text>",
      "width": 15,
      "height": 15
    },
    "description": "Powerloom Mainnet is the Layer-2 chain supporting Powerloom’s composable data network where devs, orgs, and end-users get access to ready-to-consume, affordable, and verifiable onchain datasets. It serves as the platform for generating and validating billions for ‘snapshots’ daily, i.e., the fundamental unit of Powerloom’s data markets and composed datasets."
  },
  {
    "id": "rari-mainnet",
    "name": "RARI Chain",
    "shortName": "RARI Chain",
    "caip2": "eip155:1380012617",
    "chainId": 1380012617,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Caldera",
      "status": "Mainnet",
      "layer": 3,
      "category": "consumer"
    },
    "colors": {
      "light": [
        "#B16EFF",
        "#1E1E1E"
      ],
      "dark": [
        "#B16EFF",
        "#1E1E1E"
      ],
      "darkTextOnBackground": true
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#B16EFF\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#B16EFF\">R</text>",
      "width": 15,
      "height": 15
    },
    "description": "The first creator-centric L3 with royalties built on the node level, powered by Arbitrum."
  },
  {
    "id": "sanko",
    "name": "Sanko",
    "shortName": "Sanko",
    "caip2": "eip155:1996",
    "chainId": 1996,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Caldera",
      "status": "Mainnet",
      "layer": 3,
      "category": "gaming"
    },
    "colors": {
      "light": [
        "#0367FF",
        "#0367FF"
      ],
      "dark": [
        "#0367FF",
        "#0367FF"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#0367FF\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#0367FF\">S</text>",
      "width": 15,
      "height": 15
    },
    "description": "Sanko Mainnet is a gaming ecosystem used as the blockchain hub for the Sanko gaming universe and beyond, powered by $DMT."
  },
  {
    "id": "superposition",
    "name": "Superposition ",
    "shortName": "Superpositio",
    "caip2": "eip155:55244",
    "chainId": 55244,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 3,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#1E1E1E",
        "#1E1E1E"
      ],
      "dark": [
        "#1E1E1E",
        "#1E1E1E"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#1E1E1E\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#1E1E1E\">S</text>",
      "width": 15,
      "height": 15
    },
    "description": "Superposition is the ultimate yield centric blockchain that pays users and developers to use it. Superposition offers novel incentive mechanisms such as Utility Mining and Super Assets and an native on-chain order book built using Stylus that provides shared liquidity for the ecosystem."
  },
  {
    "id": "xai",
    "name": "Xai",
    "shortName": "Xai",
    "caip2": "eip155:660279",
    "chainId": 660279,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Arbitrum One",
      "deployerTeam": "Offchain Labs",
      "status": "Mainnet",
      "layer": 3,
      "category": "gaming"
    },
    "colors": {
      "light": [
        "#F30019",
        "#87000E"
      ],
      "dark": [
        "#F30019",
        "#87000E"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#F30019\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#F30019\">X</text>",
      "width": 15,
      "height": 15
    },
    "description": "Xai was developed to enable real economies and open trade in the next generation of video games. With Xai, potentially billions of traditional gamers can own and trade valuable in-game items in their favorite games for the first time, without the need to use crypto-wallets. Anyone can support the Xai network by operating a node which allows them to receive network rewards and participate in governance. "
  },
  {
    "id": "xchain",
    "name": "XCHAIN",
    "shortName": "XCHAIN",
    "caip2": "eip155:94524",
    "chainId": 94524,
    "isOrbitChain": true,
    "orbitMetadata": {
      "parentChain": "Ethereum",
      "deployerTeam": "Conduit",
      "status": "Mainnet",
      "layer": 2,
      "category": "defi"
    },
    "colors": {
      "light": [
        "#fd0598",
        "#fd0598"
      ],
      "dark": [
        "#fd0598",
        "#fd0598"
      ],
      "darkTextOnBackground": false
    },
    "logo": {
      "body": "<circle cx=\"7.5\" cy=\"7.5\" r=\"6\" fill=\"#fd0598\" opacity=\"0.2\"/><text x=\"7.5\" y=\"10\" text-anchor=\"middle\" font-size=\"8\" font-weight=\"bold\" fill=\"#fd0598\">X</text>",
      "width": 15,
      "height": 15
    },
    "description": "XCHAIN provides high throughput, low latency, and low costs, and inherits its security directly from Ethereum. These properties allow IDEX to provide a trading experience equivalent to a centralized exchange, with instant settlement and no gas costs, along with the fund security of a decentralized exchange."
  }
];

export const ORBIT_CHAIN_IDS = new Set(ORBIT_CHAINS.map(chain => chain.caip2));

export function isOrbitChain(caip2: string): boolean {
  return ORBIT_CHAIN_IDS.has(caip2);
}

export function getOrbitChainMetadata(caip2: string) {
  return ORBIT_CHAINS.find(chain => chain.caip2 === caip2)?.orbitMetadata;
}
